<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Model\Group as AbstractedGroup;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends ).
 *
 * References :
 * working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @ORM\Entity
 * @ORM\Table(name="fos_user_group")
 *
 * @author <yourname> <youremail>
 */
class Group extends AbstractedGroup
{
  /**
   * @var int
   *
   * @ORM\Id
   * @ORM\Column(type="integer")
   * @ORM\GeneratedValue(strategy="AUTO")
   */
  protected $id;

  public function getId(): int
  {
    return $this->id;
  }

  /**
   * Represents a string representation.
   *
   * @return string
   */
  public function __toString()
  {
    return $this->getName() ?: '';
  }
}
